### ISSUE TITLE
PEM applied, site still has invalid cert

### ISSUE THREAD

**Issue by helveticade** [sintaxi/surge#251]
I'm trying to update an expired cert on my Plus custom domain. I've generated a new certificate via Lets Encrypt and created a `surge.pem` file, then used `surge ssl` to push the new certificate to my site.

```
(v2)⚡ % surge ssl                                                                 ~/site-address

    Surge - surge.sh

              email: helveticade@login.com
              token: *****************
             domain: domain.address
           pem file: surge.pem


    Success - the pem file has been applied
```

Although I'm getting a 'Success!' message, my site still serves the old certificate, which has been expired for the past 3 days. What gives?

**Comment by sintaxi** [comment]
Send over your domain. Ill look into it for you.

**Comment by helveticade** [comment]
The domain in question is shiba.computer. Thanks!

**Comment by sintaxi** [comment]
Its fixed now. sorry for the issue.

**Comment by helveticade** [comment]
Thanks for attending to this so quickly. What was the issue?

**Comment by mtt87** [comment]
Having the same issue here, I've applied successfully the `.pem` certificate but still doesn't work
https://mealseaty.ch/

I've reapplied it 3 times in the last ~1h but no luck :(

**Comment by srobertson421** [comment]
@mtt87 Did your issue ever get resolved? I'm getting something similar

**Comment by mtt87** [comment]
@srobertson421 honestly at some point I didn't have any more patience and decided to spend a couple of hours setting up a deploy with S3+Cloudfront that is not going to have any more problems in the future.

Surge sounds cool for demo or hobby projects but in my experience is not reliable for a production commercial project.

That said I hope they will make it work better because I'd love to use it in the future in production.

**Comment by sintaxi** [comment]
@mtt87 sorry for the frustration. Sometimes there can be a delay for the cert to propagate to all the edge-nodes. Usually only takes a couple hours tops. We're making this better.

**Comment by shibacomputer** [comment]
@mtt87 @srobertson421 I had my issue fixed, but with no real explanation about what happened as you can see above in this ticket.

Whilst being sensitive to the workload of @sintaxi and others on the Surge team, not having a proper explanation about why an SSL cert was failing concerns me.
